packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@clerk/shared': true
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  browser-tabs-lock: true
  bufferutil: true
  core-js: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
